Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -38,6 +38,7 @@ jobs:
          NEW_VERSION=$(mvn help:evaluate -Dexpression.project.version -q -DforceStdout | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Version bumped to $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
+         cat $GITHUB_OUTPUT || echo "Output file not found"
     - name: Commit new version
       run: |
         git config user.name "github-actions"
